#!/bin/bash

# confirm_action(){
#   read -p "${1} " -n 1 -r
#   echo
#   if [[ $REPLY =~ ^[Yy]$ ]]; then
#     shift
#     "$@"
#   fi
# }

# echo

# node_packages_outdated=$(pnpm -g outdated)


# Detect new pnpm version and upgrade
# confirm_action "Do you wish to upgrade pnpm?" echo "Upgrade pnpm"

# Detect outdated packages and update it
# [[ -n "$node_packages_outdated" ]] \
#   && confirm_action "Do you wish to update nodejs packages?" \
#   pnpm -g outdated

# Install missing nodejs packages with pnpm
node_packages=(
  typescript
  typescript-language-server
  vscode-langservers-extracted
  yaml-language-server
  eslint
  @fsouza/prettierd
  prettier-plugin-go-template
  stylelint
  bash-language-server
  @tailwindcss/language-server
  @astrojs/language-server
  dockerfile-language-server-nodejs
  cssmodules-language-server
  emmet-ls
  @johnnymorganz/stylua-bin
  pyright
  svelte-language-server
  vls
  stylelint-lsp
  intelephense
  # sql-language-server
  sql-formatter
)

node_packages_missing=()

node_packages_installed=$(pnpm -g list --depth 0)

for pkg in "${node_packages[@]}"
do
  if [[ "$node_packages_installed" != *"$pkg"* ]]; then
    node_packages_missing+=("$pkg")
  fi
done

if [[ ${#node_packages_missing} -gt 0 ]]; then
  pnpm add -g "${node_packages_missing[@]}" || echo "Error installing nodejs packages."
fi


# --- Install Rust ---
if ! command -v rustc &> /dev/null
then
    read -p "Rust is not installed. Install Rust (via rustup)? [y/N]: " confirm_rust
    if [[ "$confirm_rust" =~ ^[Yy]$ ]]; then
        echo "Installing Rust..."
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source "$HOME/.cargo/env"
    fi
fi

# --- Install Taplo ---
if ! command -v taplo &> /dev/null
then
    read -p "Taplo is not installed. Install Taplo CLI? [y/N]: " confirm_taplo
    if [[ "$confirm_taplo" =~ ^[Yy]$ ]]; then
        echo "Installing Taplo..."
        cargo install taplo-cli --locked
    fi
fi

# --- Install Treesiter-cli ---
if ! command -v tree-sitter &> /dev/null
then
    read -p "tree-sitter CLI is not installed. Install tree-sitter CLI? [y/N]: " confirm_tree_sitter
    if [[ "$confirm_tree_sitter" =~ ^[Yy]$ ]]; then
        echo "Installing tree-sitter CLI..."
        cargo install --locked tree-sitter-cli
    fi
fi
